--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 18.08.2019 19:16:43
-- Server version: 8.0.17
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE db1;

--
-- Drop table `marks`
--
DROP TABLE IF EXISTS marks;

--
-- Drop table `student`
--
DROP TABLE IF EXISTS student;

--
-- Set default database
--
USE db1;

--
-- Create table `student`
--
CREATE TABLE student (
  student_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) DEFAULT NULL,
  `group` VARCHAR(45) DEFAULT NULL,
  sex VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (student_id),
  UNIQUE INDEX UK_student_student_id(student_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `marks`
--
CREATE TABLE marks (
  marks_id INT(11) NOT NULL AUTO_INCREMENT,
  subject VARCHAR(45) DEFAULT NULL,
  mark INT(11) DEFAULT NULL,
  student_id INT(11) NOT NULL,
  PRIMARY KEY (marks_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE marks 
  ADD CONSTRAINT FK_marks_student_id2 FOREIGN KEY (student_id)
    REFERENCES student(student_id);

-- 
-- Dumping data for table student
--
INSERT INTO student VALUES
(1, 'Alexey', '123', 'm'),
(2, 'Mikhail', '123', 'm'),
(3, 'Петров', '123', 'f'),
(4, 'Алина', '123', 'f'),
(5, 'Антон', '321', 'm'),
(6, 'Сергей', '321', 'm'),
(7, 'Тимур', '321', 'm'),
(8, 'Елизавета', '321', 'f'),
(9, 'Алукард', '666', 'm'),
(10, 'Женщина-кошка', '666', 'f'),
(11, 'Харли Квинн', '666', 'f');

-- 
-- Dumping data for table marks
--
INSERT INTO marks VALUES
(1, 'Математика', 5, 1),
(2, 'Физика', 5, 10),
(3, 'Физика', 3, 9),
(4, 'Английский', 5, 5),
(5, 'Математика', 3, 2),
(6, 'Математика', 3, 4),
(7, 'Математика', 4, 6),
(8, 'Английский', 4, 11),
(9, 'Физика', 4, 11),
(10, 'Физика', 4, 3),
(11, 'Английский', 4, 3),
(12, 'Java', 5, 1),
(13, 'Java', 4, 2),
(14, 'Java', 3, 3),
(15, 'Java', 2, 4),
(16, 'Java', 4, 5),
(17, 'Java', 5, 6),
(18, 'Java', 3, 7),
(19, 'Математика', 2, 2),
(20, 'Java', 2, 2),
(21, 'Математика', 2, 11),
(22, 'Математика', 2, 9);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;